In [59]:
!pip install --upgrade category_encoders #package installation

Collecting category_encoders
  Downloading category_encoders-2.6.3-py2.py3-none-any.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB 3.5 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.23.5)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.11.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.0)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.5.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.2.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (23.2)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.6.3

In [60]:
import pandas  as pd
import category_encoders as ce
import numpy as np

In [9]:
Connec_df = pd.read_csv('Real_Estate_Sales_2001-2020_GL.csv')

<ipython-input-9-633bdaca12fb>:1: DtypeWarning: Columns (8,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  Connec_df = pd.read_csv('Real_Estate_Sales_2001-2020_GL.csv')

In [10]:
Connec_df

,Serial Number,List Year,Date Recorded,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Non Use Code,Assessor Remarks,OPM remarks,Location
0,2020348,2020,09/13/2021,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.463000,Commercial,NaN,NaN,NaN,NaN,NaN
1,20002,2020,10/02/2020,Ashford,390 TURNPIKE RD,253000.0,430000.0,0.588300,Residential,Single Family,NaN,NaN,NaN,NaN
2,200212,2020,03/09/2021,Avon,5 CHESTNUT DRIVE,130400.0,179900.0,0.724800,Residential,Condo,NaN,NaN,NaN,NaN
3,200243,2020,04/13/2021,Avon,111 NORTHINGTON DRIVE,619290.0,890000.0,0.695800,Residential,Single Family,NaN,NaN,NaN,NaN
4,200377,2020,07/02/2021,Avon,70 FAR HILLS DRIVE,862330.0,1447500.0,0.595700,Residential,Single Family,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522300,90032,2009,10/30/2009,Montville,267 MAPLE AVE,116000.0,209900.0,0.552644,Single Family,Single Family,NaN,NaN,NaN,POINT (-72.13219 41.44839)
522301,90194,2009,12/28/2009,Hartford,257 SOUTH MARSHALL ST,57690.0,147700.0,0.390589,Three Family,Three Family,25 - Other,Foreclosure related sale,NaN,NaN
522302,90551,2009,08/03/2010,Southington,355 PONDVIEW DR,122850.0,130800.0,0.939220,Single Family,Single Family,NaN,NaN,NaN,NaN
522303,900019,2009,10/16/2009,New London,65 COLMAN ST,134820.0,87000.0,1.549655,Two Family,Two Family,14 - Foreclosure,NaN,NaN,NaN
522304,900219,2009,08/19/2010,Berlin,24 G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
Dubai_df = pd.read_csv('Transactions.csv')

In [12]:
Dubai_df

,transaction_id,procedure_id,trans_group_id,trans_group_ar,trans_group_en,procedure_name_ar,procedure_name_en,instance_date,property_type_id,property_type_ar,...,rooms_en,has_parking,procedure_area,actual_worth,meter_sale_price,rent_value,meter_rent_price,no_of_parties_role_1,no_of_parties_role_2,no_of_parties_role_3
0,1-11-2001-165,11,1,مبايعات,Sales,بيع,Sell,24-02-2001,1,أرض,...,NaN,0.0,1393.55,1350000.0,968.75,NaN,NaN,1.0,1.0,0.0
1,3-9-2004-223,9,3,هبات,Gifts,هبه,Grant,13-12-2004,4,فيلا,...,NaN,0.0,1728.00,2790000.0,1614.58,NaN,NaN,1.0,1.0,0.0
2,2-13-1996-119,13,2,رهون,Mortgages,تسجيل رهن,Mortgage Registration,12-03-2001,1,أرض,...,NaN,0.0,929.03,20000000.0,21527.83,NaN,NaN,1.0,1.0,0.0
3,2-14-2005-222,14,2,رهون,Mortgages,تعديل رهن,Modify Mortgage,20-09-2005,2,مبنى,...,NaN,0.0,2673.28,25000000.0,9351.81,NaN,NaN,1.0,1.0,0.0
4,3-9-2012-874,9,3,هبات,Gifts,هبه,Grant,11-10-2012,4,فيلا,...,NaN,0.0,1541.17,9000000.0,5839.72,NaN,NaN,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84624,1-102-2012-5156,102,1,مبايعات,Sales,بيع - تسجيل مبدئى,Sell - Pre registration,26-11-2012,3,وحدة,...,1 B/R,1.0,76.64,2279202.0,29739.07,NaN,NaN,1.0,2.0,0.0
84625,1-11-2015-3050,11,1,مبايعات,Sales,بيع,Sell,16-02-2015,3,وحدة,...,Studio,1.0,45.73,1000000.0,21867.48,NaN,NaN,1.0,1.0,0.0
84626,1-11-2014-24502,11,1,مبايعات,Sales,بيع,Sell,10-11-2014,3,وحدة,...,Studio,1.0,44.45,1269730.0,28565.35,NaN,NaN,1.0,1.0,0.0
84627,1-102-2007-10849,102,1,مبايعات,Sales,بيع - تسجيل مبدئى,Sell - Pre registration,15-06-2009,3,وحدة,...,Studio,1.0,48.94,504000.0,10298.32,NaN,NaN,1.0,1.0,0.0
84628,2-13-2020-242,13,2,رهون,Mortgages,تسجيل رهن,Mortgage Registration,12-01-2020,3,وحدة,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# **Understanding the dataframes Before transformations**

In [13]:
r1,c1 = Connec_df.shape
print("Rows= ",r1,"columns= ",c1)

Rows=  522305 columns=  14

In [14]:
r2,c2 = Dubai_df.shape
print("Rows= ",r1,"columns= ",c1)

Rows=  522305 columns=  14

In [15]:
Connec_df.describe()

,Serial Number,List Year,Assessed Value,Sale Amount,Sales Ratio
count,5.223050e+05,522305.000000,5.223040e+05,5.223040e+05,5.223040e+05
mean,4.710658e+05,2006.206879,2.370522e+05,3.847153e+05,1.722433e+01
std,7.900159e+06,5.667209,1.201582e+06,7.053687e+06,2.582367e+03
min,0.000000e+00,2001.000000,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.218600e+04,2003.000000,7.308750e+04,1.450000e+05,4.205125e-01
50%,4.098400e+04,2004.000000,1.171800e+05,2.295000e+05,5.195000e-01
75%,7.000500e+04,2007.000000,1.964900e+05,3.665000e+05,6.484038e-01
max,2.000500e+09,2020.000000,1.229354e+08,5.000000e+09,1.226420e+06

In [16]:
Dubai_df.describe

<bound method NDFrame.describe of          transaction_id  procedure_id  trans_group_id trans_group_ar  \
0         1-11-2001-165            11               1        مبايعات
1          3-9-2004-223             9               3           هبات
2         2-13-1996-119            13               2           رهون
3         2-14-2005-222            14               2           رهون
4          3-9-2012-874             9               3           هبات
...                 ...           ...             ...            ...
84624   1-102-2012-5156           102               1        مبايعات
84625    1-11-2015-3050            11               1        مبايعات
84626   1-11-2014-24502            11               1        مبايعات
84627  1-102-2007-10849           102               1        مبايعات
84628     2-13-2020-242            13               2           رهون

      trans_group_en  procedure_name_ar        procedure_name_en  \
0              Sales                بيع                     Sell
1              Gifts                هبه                    Grant
2          Mortgages          تسجيل رهن    Mortgage Registration
3          Mortgages          تعديل رهن          Modify Mortgage
4              Gifts                هبه                    Grant
...              ...                ...                      ...
84624          Sales  بيع - تسجيل مبدئى  Sell - Pre registration
84625          Sales                بيع                     Sell
84626          Sales                بيع                     Sell
84627          Sales  بيع - تسجيل مبدئى  Sell - Pre registration
84628      Mortgages          تسجيل رهن    Mortgage Registration

      instance_date  property_type_id property_type_ar  ... rooms_en  \
0        24-02-2001                 1              أرض  ...      NaN
1        13-12-2004                 4             فيلا  ...      NaN
2        12-03-2001                 1              أرض  ...      NaN
3        20-09-2005                 2             مبنى  ...      NaN
4        11-10-2012                 4             فيلا  ...      NaN
...             ...               ...              ...  ...      ...
84624    26-11-2012                 3             وحدة  ...    1 B/R
84625    16-02-2015                 3             وحدة  ...   Studio
84626    10-11-2014                 3             وحدة  ...   Studio
84627    15-06-2009                 3             وحدة  ...   Studio
84628    12-01-2020                 3             وحدة  ...      NaN

       has_parking procedure_area actual_worth meter_sale_price rent_value  \
0              0.0        1393.55    1350000.0           968.75        NaN
1              0.0        1728.00    2790000.0          1614.58        NaN
2              0.0         929.03   20000000.0         21527.83        NaN
3              0.0        2673.28   25000000.0          9351.81        NaN
4              0.0        1541.17    9000000.0          5839.72        NaN
...            ...            ...          ...              ...        ...
84624          1.0          76.64    2279202.0         29739.07        NaN
84625          1.0          45.73    1000000.0         21867.48        NaN
84626          1.0          44.45    1269730.0         28565.35        NaN
84627          1.0          48.94     504000.0         10298.32        NaN
84628          NaN            NaN          NaN              NaN        NaN

       meter_rent_price no_of_parties_role_1 no_of_parties_role_2  \
0                   NaN                  1.0                  1.0
1                   NaN                  1.0                  1.0
2                   NaN                  1.0                  1.0
3                   NaN                  1.0                  1.0
4                   NaN                  1.0                  1.0
...                 ...                  ...                  ...
84624               NaN                  1.0                  2.0
84625               NaN                  1.0                  1.0
84626               NaN                  1.0                  1.0
84627               NaN                  1.0                  1.0
84628               NaN                  NaN                  NaN

       no_of_parties_role_3
0                       0.0
1                       0.0
2                       0.0
3                       0.0
4                       0.0
...                     ...
84624                   0.0
84625                   0.0
84626                   0.0
84627                   0.0
84628                   NaN

[84629 rows x 46 columns]>

# **Chooosing the required columns for analysis.**

In [139]:
df_Conn = Connec_df[['Date Recorded', 'Sale Amount', 'Property Type','Residential Type','Serial Number']]

In [140]:
df_Conn

,Date Recorded,Sale Amount,Property Type,Residential Type,Serial Number
0,09/13/2021,325000.0,Commercial,NaN,2020348
1,10/02/2020,430000.0,Residential,Single Family,20002
2,03/09/2021,179900.0,Residential,Condo,200212
3,04/13/2021,890000.0,Residential,Single Family,200243
4,07/02/2021,1447500.0,Residential,Single Family,200377
...,...,...,...,...,...
522300,10/30/2009,209900.0,Single Family,Single Family,90032
522301,12/28/2009,147700.0,Three Family,Three Family,90194
522302,08/03/2010,130800.0,Single Family,Single Family,90551
522303,10/16/2009,87000.0,Two Family,Two Family,900019
522304,08/19/2010,NaN,NaN,NaN,900219

In [141]:
df_Dub = Dubai_df[['instance_date','property_type_en','property_usage_en','actual_worth','transaction_id']]

In [142]:
df_Dub

,instance_date,property_type_en,property_usage_en,actual_worth,transaction_id
0,24-02-2001,Land,Commercial,1350000.0,1-11-2001-165
1,13-12-2004,Villa,Commercial,2790000.0,3-9-2004-223
2,12-03-2001,Land,Commercial,20000000.0,2-13-1996-119
3,20-09-2005,Building,Residential / Commercial,25000000.0,2-14-2005-222
4,11-10-2012,Villa,Residential,9000000.0,3-9-2012-874
...,...,...,...,...,...
84624,26-11-2012,Unit,Residential,2279202.0,1-102-2012-5156
84625,16-02-2015,Unit,Residential,1000000.0,1-11-2015-3050
84626,10-11-2014,Unit,Residential,1269730.0,1-11-2014-24502
84627,15-06-2009,Unit,Residential,504000.0,1-102-2007-10849
84628,12-01-2020,Unit,Residential,NaN,2-13-2020-242

# **Understanding the dataframes we are going to deal with in our analysis.**

In [88]:
df_Conn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522305 entries, 0 to 522304
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date Recorded     522303 non-null  object
 1   Sale Amount       522304 non-null  float64
 2   Property Type     179873 non-null  object
 3   Residential Type  174010 non-null  object
 4   Serial Number     522305 non-null  int64
dtypes: float64(1), int64(1), object(3)
memory usage: 19.9+ MB

In [89]:
missing_values_count = df_Conn.isnull().sum()
missing_values_count

Date Recorded            2
Sale Amount              1
Property Type       342432
Residential Type    348295
Serial Number            0
dtype: int64

In [90]:
df_Dub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84629 entries, 0 to 84628
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   instance_date      84629 non-null  object
 1   property_type_en   84629 non-null  object
 2   property_usage_en  84629 non-null  object
 3   actual_worth       84302 non-null  float64
 4   transaction_id     84629 non-null  object
dtypes: float64(1), object(4)
memory usage: 3.2+ MB

In [91]:
missing_values_count2 = df_Dub.isnull().sum()
missing_values_count2

instance_date          0
property_type_en       0
property_usage_en      0
actual_worth         327
transaction_id         0
dtype: int64

# **The Connecttiut has alot of missing values, so the best solution is to reduce the number of rows. Property type and Residential type have the most null values therefore we deal with them**

In [92]:
df_Conn = df_Conn.dropna(subset=['Property Type', 'Residential Type'])

In [93]:
df_Conn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 174010 entries, 1 to 522303
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date Recorded     174010 non-null  object
 1   Sale Amount       174010 non-null  float64
 2   Property Type     174010 non-null  object
 3   Residential Type  174010 non-null  object
 4   Serial Number     174010 non-null  int64
dtypes: float64(1), int64(1), object(3)
memory usage: 8.0+ MB

In [94]:
df_Conn

,Date Recorded,Sale Amount,Property Type,Residential Type,Serial Number
1,10/02/2020,430000.0,Residential,Single Family,20002
2,03/09/2021,179900.0,Residential,Condo,200212
3,04/13/2021,890000.0,Residential,Single Family,200243
4,07/02/2021,1447500.0,Residential,Single Family,200377
5,12/09/2020,1250000.0,Residential,Single Family,200109
...,...,...,...,...,...
522299,10/16/2009,176000.0,Single Family,Single Family,90056
522300,10/30/2009,209900.0,Single Family,Single Family,90032
522301,12/28/2009,147700.0,Three Family,Three Family,90194
522302,08/03/2010,130800.0,Single Family,Single Family,90551
522303,10/16/2009,87000.0,Two Family,Two Family,900019

## **Now we work on the Dubai Dubai dataframe to replace its null values instead of dropping the rows, this is because the null values are little.**

In [144]:
 # function to fill missing values with a random sample, we larened it in thye lab.
def impute_na(data, variable):

    df = data.copy()


    df[variable+'_random'] = df[variable]



    random_sample = df[variable].dropna().sample(df[variable].isnull().sum(), random_state=0)


    random_sample.index = df[df[variable].isnull()].index
    df.loc[df[variable].isnull(), variable+'_random'] = random_sample

    return df[variable+'_random']

In [152]:
df_Dub['Actual_worth'] = impute_na(df_Dub,'actual_worth')
df_Dub = df_Dub.drop('actual_worth', axis=1)

KeyError: ignored

In [153]:
df_Dub = df_Dub.drop('actual_worth1', axis=1)

In [154]:
df_Dub

,instance_date,property_type_en,property_usage_en,transaction_id,Actual_worth
0,24-02-2001,Land,Commercial,1-11-2001-165,1350000.0
1,13-12-2004,Villa,Commercial,3-9-2004-223,2790000.0
2,12-03-2001,Land,Commercial,2-13-1996-119,20000000.0
3,20-09-2005,Building,Residential / Commercial,2-14-2005-222,25000000.0
4,11-10-2012,Villa,Residential,3-9-2012-874,9000000.0
...,...,...,...,...,...
84624,26-11-2012,Unit,Residential,1-102-2012-5156,2279202.0
84625,16-02-2015,Unit,Residential,1-11-2015-3050,1000000.0
84626,10-11-2014,Unit,Residential,1-11-2014-24502,1269730.0
84627,15-06-2009,Unit,Residential,1-102-2007-10849,504000.0
84628,12-01-2020,Unit,Residential,2-13-2020-242,16000000.0

# **After we create a new column that replaces the null values in the Actual_worth column, we get rid of the null values actual worth column**

In [155]:
df_Dub.isnull().sum()

instance_date        0
property_type_en     0
property_usage_en    0
transaction_id       0
Actual_worth         0
dtype: int64

In [157]:
df_Dub

,instance_date,property_type_en,property_usage_en,transaction_id,Actual_worth
0,24-02-2001,Land,Commercial,1-11-2001-165,1350000.0
1,13-12-2004,Villa,Commercial,3-9-2004-223,2790000.0
2,12-03-2001,Land,Commercial,2-13-1996-119,20000000.0
3,20-09-2005,Building,Residential / Commercial,2-14-2005-222,25000000.0
4,11-10-2012,Villa,Residential,3-9-2012-874,9000000.0
...,...,...,...,...,...
84624,26-11-2012,Unit,Residential,1-102-2012-5156,2279202.0
84625,16-02-2015,Unit,Residential,1-11-2015-3050,1000000.0
84626,10-11-2014,Unit,Residential,1-11-2014-24502,1269730.0
84627,15-06-2009,Unit,Residential,1-102-2007-10849,504000.0
84628,12-01-2020,Unit,Residential,2-13-2020-242,16000000.0

# **Now lets check for any duplicated rows and drop them.**

In [158]:
df_Conn.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
522300    False
522301    False
522302    False
522303    False
522304    False
Length: 522305, dtype: bool

In [159]:
df_Conn.duplicated().sum()

420

In [160]:
df_Conn = df_Conn.drop_duplicates()

df_Conn

,Date Recorded,Sale Amount,Property Type,Residential Type,Serial Number
0,09/13/2021,325000.0,Commercial,NaN,2020348
1,10/02/2020,430000.0,Residential,Single Family,20002
2,03/09/2021,179900.0,Residential,Condo,200212
3,04/13/2021,890000.0,Residential,Single Family,200243
4,07/02/2021,1447500.0,Residential,Single Family,200377
...,...,...,...,...,...
522300,10/30/2009,209900.0,Single Family,Single Family,90032
522301,12/28/2009,147700.0,Three Family,Three Family,90194
522302,08/03/2010,130800.0,Single Family,Single Family,90551
522303,10/16/2009,87000.0,Two Family,Two Family,900019
522304,08/19/2010,NaN,NaN,NaN,900219

In [161]:
df_Dub.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
84624    False
84625    False
84626    False
84627    False
84628    False
Length: 84629, dtype: bool

In [162]:
df_Dub.duplicated().sum()

0

In [163]:
df_Dub = df_Dub.drop_duplicates()

df_Dub

,instance_date,property_type_en,property_usage_en,transaction_id,Actual_worth
0,24-02-2001,Land,Commercial,1-11-2001-165,1350000.0
1,13-12-2004,Villa,Commercial,3-9-2004-223,2790000.0
2,12-03-2001,Land,Commercial,2-13-1996-119,20000000.0
3,20-09-2005,Building,Residential / Commercial,2-14-2005-222,25000000.0
4,11-10-2012,Villa,Residential,3-9-2012-874,9000000.0
...,...,...,...,...,...
84624,26-11-2012,Unit,Residential,1-102-2012-5156,2279202.0
84625,16-02-2015,Unit,Residential,1-11-2015-3050,1000000.0
84626,10-11-2014,Unit,Residential,1-11-2014-24502,1269730.0
84627,15-06-2009,Unit,Residential,1-102-2007-10849,504000.0
84628,12-01-2020,Unit,Residential,2-13-2020-242,16000000.0

# **Now we check each column Unique values so we can know which ones best fits for encoding and what type of encoding should we use for it.**

# **Lets start with Connectiut dataframe.**

In [164]:
df_Conn['Residential Type'].nunique()

5

# **Resdential Type has the least unique varibles, therefore we will encode it with ordinal encoding to avoid sparsity and because they are categorical dtypes.**

In [165]:
encoder = ce.OrdinalEncoder(cols = ['Residential Type'])
df_Conn = encoder.fit_transform(df_Conn)
df_Conn

,Date Recorded,Sale Amount,Property Type,Residential Type,Serial Number
0,09/13/2021,325000.0,Commercial,6,2020348
1,10/02/2020,430000.0,Residential,1,20002
2,03/09/2021,179900.0,Residential,2,200212
3,04/13/2021,890000.0,Residential,1,200243
4,07/02/2021,1447500.0,Residential,1,200377
...,...,...,...,...,...
522300,10/30/2009,209900.0,Single Family,1,90032
522301,12/28/2009,147700.0,Three Family,4,90194
522302,08/03/2010,130800.0,Single Family,1,90551
522303,10/16/2009,87000.0,Two Family,3,900019
522304,08/19/2010,NaN,NaN,6,900219

# **Now we start looking for a good column in the dubai dataframe that has less unique varibles**

In [166]:
df_Dub['property_type_en'].nunique()

4

# **Now we apply BaseN encoder on the dubai dataframe for the property type variable**

In [167]:
encoder = ce.BaseNEncoder(cols=['property_type_en'], base = 3)
df_Dub = encoder.fit_transform(df_Dub)
df_Dub

,instance_date,property_type_en_0,property_type_en_1,property_usage_en,transaction_id,Actual_worth
0,24-02-2001,0,1,Commercial,1-11-2001-165,1350000.0
1,13-12-2004,0,2,Commercial,3-9-2004-223,2790000.0
2,12-03-2001,0,1,Commercial,2-13-1996-119,20000000.0
3,20-09-2005,1,0,Residential / Commercial,2-14-2005-222,25000000.0
4,11-10-2012,0,2,Residential,3-9-2012-874,9000000.0
...,...,...,...,...,...,...
84624,26-11-2012,1,1,Residential,1-102-2012-5156,2279202.0
84625,16-02-2015,1,1,Residential,1-11-2015-3050,1000000.0
84626,10-11-2014,1,1,Residential,1-11-2014-24502,1269730.0
84627,15-06-2009,1,1,Residential,1-102-2007-10849,504000.0
84628,12-01-2020,1,1,Residential,2-13-2020-242,16000000.0

# **Here is some additional information about the datasets:**

Dubai:

In [168]:
print("Count of values in Actual worth ", df_Dub['Actual_worth'].count())

print("Mean of values in Actual worth ",df_Dub['Actual_worth'].mean())

print("Median of values in Actual worth ",df_Dub['Actual_worth'].median())

print("Maximum value in Actual worth ",df_Dub['Actual_worth'].max())

print("Minimum value in Actual worth ",df_Dub['Actual_worth'].min())

print("standard deviation of values in Actual worth ",df_Dub['Actual_worth'].std())

Count of values in Actual worth  84629
Mean of values in Actual worth  2581825.978305309
Median of values in Actual worth  1250000.0
Maximum value in Actual worth  98669779.0
Minimum value in Actual worth  1.0
standard deviation of values in Actual worth  6043206.740962927

Connectiut:

In [169]:
print("Count of values in Sale Amount ", df_Conn['Sale Amount'].count())

print("Mean of values in Sale Amount ",df_Conn['Sale Amount'].mean())

print("Median of values in Sale Amount ",df_Conn['Sale Amount'].median())

print("Maximum value in Sale Amount ",df_Conn['Sale Amount'].max())

print("Minimum value in Sale Amount ",df_Conn['Sale Amount'].min())

print("standard deviation of values in Sale Amount ",df_Conn['Sale Amount'].std())

Count of values in Sale Amount  521884
Mean of values in Sale Amount  384840.14613481157
Median of values in Sale Amount  229800.0
Maximum value in Sale Amount  5000000000.0
Minimum value in Sale Amount  0.0
standard deviation of values in Sale Amount  7056522.5134406425

# ***And thats it for the transformation phase, Thank you.***